version: '3.8'
services:
  app:
    build: .
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/userDB"
      SPRING_DATASOURCE_USERNAME: "user"
      SPRING_DATASOURCE_PASSWORD: "password"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d userDB" ]
      interval: 10s
      retries: 3
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userDB
    ports:
      - "5432:5432"