version: '3.8'

services:
  shop-service:
    build: ./shop-service
    container_name: shop-service
    ports:
      - "8000:8000"
    environment:
      - STAND_SERVICE_URL=http://stand-service:8080
      - USER_SERVICE_URL=http://user-service:8081
      - HOST=0.0.0.0
      - PORT=8000
      - CORS_ORIGINS=*
    networks:
      - bookshop-network
    depends_on:
      - user-service
      - stand-service

  user-service:
    build: ./user-service/user-service
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-service-db:5432/userdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - bookshop-network
    depends_on:
      user-service-db:
        condition: service_healthy

  user-service-db:
    image: postgres:latest
    container_name: user-service-db
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - bookshop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  stand-service:
    build: ./stand-service/stand-service
    container_name: stand-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stand-service-db:5432/standdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - bookshop-network
    depends_on:
      stand-service-db:
        condition: service_healthy

  stand-service-db:
    image: postgres:latest
    container_name: stand-service-db
    environment:
      - POSTGRES_DB=standdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    networks:
      - bookshop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  bookshop-network:
    name: bookshop-network
    driver: bridge 